services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    deploy:
      labels:
        prometheus-job: traefik
        prometheus_port: 8080
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        delay: 5s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 3024M
          cpus: "1.8"
        reservations:
          memory: 1024M
          cpus: "0.5"
    security_opt:
      - no-new-privileges:true

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - ./certs:/etc/certs
      - ./logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      # Provider Docker - ESSENCIAL para ler labels dos containers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=azap_net"
      
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/dynamic/tls.yaml"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Logs JSON no stdout (para docker compose logs)
      - "--log.level=INFO"
      - "--log.format=json"
      # Observability 
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--metrics.prometheus=true"

      # Let's Encrypt ACME Configuration
      - --certificatesresolvers.letsencrypt.acme.email=suporte@azapfy.com.br
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    networks:
      - azap_net

  redis_back:
    image: redis:latest
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    deploy:
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        delay: 5s
      resources:
        reservations:
          memory: 1012M
          cpus: "0.5"
        limits:
          memory: 3012M
          cpus: "1.8"
    command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
    networks:
      - azap_net

  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - azap_net

volumes:
  postgres_data:
    driver: local

networks:
  azap_net:
    external: true